export const productConstants = {
  PRODUCT_SELECT_SUCCESS: 'PRODUCT_SELECT_SUCCESS',
  PRODUCT_SELECT_FAILURE: 'PRODUCT_SELECT_FAILURE',

  PRODUCT_GET_PRODUCTS_SUCCESS: 'PRODUCT_GET_PRODUCTS_SUCCESS',
  PRODUCT_GET_PRODUCTS_FAILURE: 'PRODUCT_GET_PRODUCTS_FAILURE',
};