export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  REGISTRATION_REQUEST: 'USERS_REGISTRATION_REQUEST',
  REGISTRATION_SUCCESS: 'USERS_REGISTRATION_SUCCESS',
  REGISTRATION_FAILURE: 'USERS_REGISTRATION_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  REFRESH_REQUEST: 'USERS_REFRESH_REQUEST',
  REFRESH_SUCCESS: 'USERS_REFRESH_SUCCESS',
  REFRESH_FAILURE: 'USERS_REFRESH_FAILURE',

  TEAM_ADD_SUCCESS: 'USERS_TEAM_ADD',
  TEAM_ADD_FAILURE: 'USERS_TEAM_FAILURE'
}
